# Generated by Django 3.0 on 2022-02-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_time',
            field=models.DateField(null=True, verbose_name='出版时间'),
        ),
    ]
